export const SOS_ESCALATION_SECONDS = Number(process.env.SOS_ESCALATION_SECONDS ?? 60);

export interface SosInput {
  /** Generated by the app once per press and reused on every retry, so a flaky network never makes duplicates. */
  idempotencyKey: string;
  userId: string;
  role: 'rider' | 'driver';
  location?: { lat: number; lng: number; accuracyM?: number };
  /** Optional hint; the server resolves the real active ride itself and never trusts this blindly. */
  rideId?: string;
}

export interface SosStored {
  id: string;
  /** True once the alert is durably in Postgres. The app may say "received" only when this is true. */
  stored: true;
  duplicate: boolean;
}

/** Live alert to staff in the admin portal (Redis pub/sub -> Socket.IO gateway). */
export interface StaffAlerter {
  newSos(sos: { id: string; role: string; rideId: string | null; lat?: number; lng?: number }): Promise<void>;
}
/** Second channel: SMS to the on-call phone. */
export interface SmsSender {
  send(toPhone: string, text: string): Promise<void>;
}
/** Third step: phone escalation when nobody acknowledged in time. */
export interface CallEscalator {
  call(toPhone: string, sosId: string): Promise<void>;
}
/** Tells the person who pressed SOS that staff acknowledged it. */
export interface SosAckNotifier {
  acknowledged(userId: string, sosId: string): Promise<void>;
}

export const STAFF_ALERTER = Symbol('STAFF_ALERTER');
export const SMS_SENDER = Symbol('SMS_SENDER');
export const CALL_ESCALATOR = Symbol('CALL_ESCALATOR');
export const SOS_ACK_NOTIFIER = Symbol('SOS_ACK_NOTIFIER');
