import { Inject, Injectable, Logger } from '@nestjs/common';
import { Pool } from 'pg';
import { PG_POOL } from '../common/infra.module';
import { LedgerService } from '../ledger/ledger.service';
import { planPayoutPaid, planPayoutRequest, planPayoutReversal } from '../ledger/postings';
import {
  BankDestination,
  PAYOUT_MIN_KOBO,
  PAYOUT_PROVIDER,
  PAYOUT_STUCK_SECONDS,
  PayoutProvider,
  TransferRejectedError,
} from './payments.types';

export class SelfApprovalError extends Error {
  constructor(what = 'payout') {
    super(`a ${what} must be approved by someone other than the person who requested it`);
  }
}
export class PayoutStateError extends Error {}

export interface PayoutRequestInput {
  driverId: string;
  amountKobo: number;
  bank: BankDestination;
  /** Generated by the client once per tap and reused on every retry. */
  idempotencyKey: string;
  /** The driver, or the staff member acting for them. */
  requestedBy: string;
}

@Injectable()
export class PayoutsService {
  private readonly log = new Logger(PayoutsService.name);

  constructor(
    @Inject(PG_POOL) private readonly pool: Pool,
    @Inject(PAYOUT_PROVIDER) private readonly provider: PayoutProvider,
    private readonly ledger: LedgerService,
  ) {}

  /**
   * Ask to withdraw. The money leaves the driver wallet immediately (so it cannot be withdrawn twice) and waits in
   * platform:payout until a second person approves and the transfer lands. Fails with InsufficientFundsError
   * if the wallet cannot cover it, e.g. a driver whose cash commission debt has taken the balance below zero.
   */
  async request(input: PayoutRequestInput): Promise<{ id: string; duplicate: boolean }> {
    const { driverId, amountKobo, bank } = input;
    if (!Number.isSafeInteger(amountKobo) || amountKobo < PAYOUT_MIN_KOBO) {
      throw new RangeError(`payout must be a whole number of kobo, at least ${PAYOUT_MIN_KOBO}`);
    }
    if (!/^[0-9]{10}$/.test(bank.accountNumber)) throw new RangeError('account number must be 10 digits');

    return this.ledger.withTransaction(async (client) => {
      const driver = await client.query(`SELECT 1 FROM users WHERE id = $1 AND role = 'driver'`, [driverId]);
      if (!driver.rowCount) throw new Error(`${driverId} is not a driver`);
      await this.ledger.ensureWallet(client, driverId);

      const inserted = await client.query(
        `INSERT INTO payout_requests (driver_id, amount_kobo, bank_code, account_number, account_name, idempotency_key, requested_by)
         VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (idempotency_key) DO NOTHING RETURNING id`,
        [driverId, amountKobo, bank.bankCode, bank.accountNumber, bank.accountName, input.idempotencyKey, input.requestedBy],
      );
      if (!inserted.rowCount) {
        const existing = await client.query(`SELECT id, driver_id, amount_kobo FROM payout_requests WHERE idempotency_key = $1`, [input.idempotencyKey]);
        const row = existing.rows[0];
        if (row.driver_id !== driverId || Number(row.amount_kobo) !== amountKobo) {
          throw new PayoutStateError('idempotency key was already used for a different payout');
        }
        return { id: row.id as string, duplicate: true };
      }
      const id = inserted.rows[0].id as string;
      await this.ledger.post(client, {
        kind: 'payout_request',
        reference: id,
        idempotencyKey: `payout_request:${id}`,
        postings: planPayoutRequest(driverId, amountKobo),
      });
      return { id, duplicate: false };
    });
  }

  /** Second approver. Re-approving is a no-op; approving your own request is refused here and again by the database. */
  async approve(payoutId: string, approverId: string): Promise<boolean> {
    const { rows } = await this.pool.query(`SELECT requested_by, status FROM payout_requests WHERE id = $1`, [payoutId]);
    const payout = rows[0];
    if (!payout) throw new PayoutStateError(`payout ${payoutId} not found`);
    if (payout.requested_by === approverId) throw new SelfApprovalError();
    if (payout.status !== 'PENDING_APPROVAL') {
      if (payout.status === 'APPROVED') return false;
      throw new PayoutStateError(`payout ${payoutId} is ${payout.status} and cannot be approved`);
    }
    const res = await this.pool.query(
      `UPDATE payout_requests SET status = 'APPROVED', approved_by = $2, approved_at = now(), updated_at = now()
        WHERE id = $1 AND status = 'PENDING_APPROVAL'`,
      [payoutId, approverId],
    );
    return (res.rowCount ?? 0) > 0;
  }

  /** Refuse a payout that has not been sent yet and return the money to the driver wallet. */
  async reject(payoutId: string, staffId: string, reason: string): Promise<boolean> {
    return this.ledger.withTransaction(async (client) => {
      const res = await client.query(
        `UPDATE payout_requests SET status = 'REJECTED', rejected_reason = $2, updated_at = now(), settled_at = now()
          WHERE id = $1 AND status IN ('PENDING_APPROVAL', 'APPROVED') RETURNING driver_id, amount_kobo`,
        [payoutId, reason],
      );
      if (!res.rowCount) return false;
      await this.reverse(client, payoutId, res.rows[0].driver_id, Number(res.rows[0].amount_kobo));
      this.log.log(`payout ${payoutId} rejected by ${staffId}: ${reason}`);
      return true;
    });
  }

  /**
   * Send approved payouts. Each is claimed (PROCESSING + a stable provider reference) and committed BEFORE the
   * provider is called, so a crash or retry can never send the same payout under a new reference.
   */
  async sendApproved(limit = 20): Promise<number> {
    let sent = 0;
    for (let i = 0; i < limit; i++) {
      const claimed = await this.claimNext();
      if (!claimed) break;
      sent++;
      try {
        const res = await this.provider.transfer({
          reference: claimed.reference,
          amountKobo: claimed.amountKobo,
          bank: claimed.bank,
          reason: '9jaRide driver payout',
        });
        if (res.status === 'SUCCESS') await this.markPaid(claimed.id);
      } catch (e) {
        if (e instanceof TransferRejectedError) {
          await this.fail(claimed.id, e.message);
        } else {
          // Unknown outcome (timeout, 5xx). Do NOT refund: the money may have gone. Reconciliation asks the provider.
          this.log.error(`payout ${claimed.id}: transfer outcome unknown, left PROCESSING: ${e}`);
        }
      }
    }
    return sent;
  }

  private async claimNext() {
    return this.ledger.withTransaction(async (client) => {
      const { rows } = await client.query(
        `SELECT id, amount_kobo, bank_code, account_number, account_name FROM payout_requests
          WHERE status = 'APPROVED' ORDER BY approved_at LIMIT 1 FOR UPDATE SKIP LOCKED`,
      );
      const p = rows[0];
      if (!p) return null;
      const reference = `payout_${p.id}`;
      await client.query(
        `UPDATE payout_requests SET status = 'PROCESSING', provider_reference = $2, processing_at = now(), updated_at = now() WHERE id = $1`,
        [p.id, reference],
      );
      return {
        id: p.id as string,
        reference,
        amountKobo: Number(p.amount_kobo),
        bank: { bankCode: p.bank_code, accountNumber: p.account_number, accountName: p.account_name },
      };
    });
  }

  /** The provider confirmed the transfer. Idempotent. */
  async markPaid(payoutId: string): Promise<boolean> {
    return this.ledger.withTransaction(async (client) => {
      const res = await client.query(
        `UPDATE payout_requests SET status = 'PAID', settled_at = now(), updated_at = now()
          WHERE id = $1 AND status = 'PROCESSING' RETURNING amount_kobo`,
        [payoutId],
      );
      if (!res.rowCount) return false;
      await this.ledger.post(client, {
        kind: 'payout_paid',
        reference: payoutId,
        idempotencyKey: `payout_paid:${payoutId}`,
        postings: planPayoutPaid(Number(res.rows[0].amount_kobo)),
      });
      return true;
    });
  }

  /** The provider definitively did not send it. Refund the wallet. Idempotent. */
  async fail(payoutId: string, reason: string): Promise<boolean> {
    return this.ledger.withTransaction(async (client) => {
      const res = await client.query(
        `UPDATE payout_requests SET status = 'FAILED', failure_reason = $2, settled_at = now(), updated_at = now()
          WHERE id = $1 AND status IN ('APPROVED', 'PROCESSING') RETURNING driver_id, amount_kobo`,
        [payoutId, reason],
      );
      if (!res.rowCount) return false;
      await this.reverse(client, payoutId, res.rows[0].driver_id, Number(res.rows[0].amount_kobo));
      return true;
    });
  }

  private reverse(client: import('pg').PoolClient, payoutId: string, driverId: string, amountKobo: number) {
    return this.ledger.post(client, {
      kind: 'payout_reverse',
      reference: payoutId,
      idempotencyKey: `payout_reverse:${payoutId}`,
      postings: planPayoutReversal(driverId, amountKobo),
    });
  }

  private static readonly COLUMNS = `id, driver_id, amount_kobo, bank_code, account_number, account_name, status,
    requested_by, approved_by, approved_at, rejected_reason, failure_reason, created_at, settled_at`;

  private present(r: any) {
    return {
      id: r.id,
      driverId: r.driver_id,
      amountKobo: Number(r.amount_kobo),
      bankCode: r.bank_code,
      accountNumber: r.account_number,
      accountName: r.account_name,
      status: r.status,
      requestedBy: r.requested_by,
      approvedBy: r.approved_by,
      approvedAt: r.approved_at,
      rejectedReason: r.rejected_reason,
      failureReason: r.failure_reason,
      createdAt: r.created_at,
      settledAt: r.settled_at,
    };
  }

  async listForDriver(driverId: string) {
    const { rows } = await this.pool.query(
      `SELECT ${PayoutsService.COLUMNS} FROM payout_requests WHERE driver_id = $1 ORDER BY created_at DESC LIMIT 100`,
      [driverId],
    );
    return rows.map((r) => this.present(r));
  }

  async listByStatus(status?: string) {
    const { rows } = await this.pool.query(
      `SELECT ${PayoutsService.COLUMNS} FROM payout_requests WHERE ($1::text IS NULL OR status = $1) ORDER BY created_at DESC LIMIT 200`,
      [status ?? null],
    );
    return rows.map((r) => this.present(r));
  }

  /** Ask the provider what happened to a payout and apply it. Used by the webhook and by reconciliation. */
  async refreshFromProvider(providerReference: string): Promise<string> {
    const { rows } = await this.pool.query(`SELECT id, status, EXTRACT(EPOCH FROM now() - processing_at)::float8 AS age_s FROM payout_requests WHERE provider_reference = $1`, [providerReference]);
    const payout = rows[0];
    if (!payout) return 'unknown_reference';
    if (payout.status !== 'PROCESSING') return 'duplicate';

    const status = await this.provider.verifyTransfer(providerReference);
    if (status === 'SUCCESS') return (await this.markPaid(payout.id)) ? 'paid' : 'duplicate';
    if (status === 'FAILED') return (await this.fail(payout.id, 'provider reported the transfer failed')) ? 'failed' : 'duplicate';
    if (status === 'NOT_FOUND') {
      if (payout.age_s < PAYOUT_STUCK_SECONDS) return 'pending';
      // The provider has never heard of our stable reference, so the transfer was never created. Safe to refund.
      return (await this.fail(payout.id, 'transfer never reached the provider')) ? 'failed' : 'duplicate';
    }
    return 'pending';
  }
}
